# Generated by Django 4.0.4 on 2022-05-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_workoutplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='repetitions',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets',
        ),
        migrations.AddField(
            model_name='user',
            name='workout_plans',
            field=models.ManyToManyField(to='base.workoutplan'),
        ),
    ]
