# Generated by Django 4.0.4 on 2022-05-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_exercise_repetitions_remove_exercise_sets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='workout_plans',
            new_name='workoutplans',
        ),
    ]
