# Generated by Django 4.0.4 on 2022-05-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_workout_plans_user_workoutplans'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='repetitions',
            field=models.JSONField(blank=True, default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='sets',
            field=models.JSONField(blank=True, default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='workoutplans',
            field=models.ManyToManyField(blank=True, to='base.workoutplan'),
        ),
    ]
