# Generated by Django 4.0.4 on 2022-05-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_history_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='workoutplan_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
