# Generated by Django 4.0.4 on 2022-05-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_history_workoutplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='history',
            field=models.ManyToManyField(blank=True, to='base.history'),
        ),
    ]
